CREATE TABLE IF NOT EXISTS hospitals (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  hospital_code VARCHAR(50) NOT NULL UNIQUE,
  hospital_name VARCHAR(255) NOT NULL,
  location VARCHAR(500),
  subdomain VARCHAR(100) UNIQUE,
  tenant_db_name VARCHAR(100) UNIQUE,
  custom_domain VARCHAR(255) UNIQUE,
  domain_verification_token VARCHAR(120),
  domain_verification_status VARCHAR(30) DEFAULT 'NOT_CONFIGURED',
  domain_verified_at DATETIME,
  certificate_status VARCHAR(30) DEFAULT 'NOT_REQUESTED',
  certificate_requested_at DATETIME,
  certificate_issued_at DATETIME,
  certificate_expires_at DATETIME,
  last_domain_verification_error VARCHAR(1000),
  last_certificate_error VARCHAR(1000),
  logo_url LONGTEXT,
  website_url VARCHAR(255),
  facebook_url VARCHAR(255),
  twitter_url VARCHAR(255),
  instagram_url VARCHAR(255),
  linkedin_url VARCHAR(255),
  contact_email VARCHAR(100),
  billing_email VARCHAR(100),
  contact_phone VARCHAR(20),
  onboarding_status VARCHAR(30) DEFAULT 'PENDING',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

