ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS website_url VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS twitter_url VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS billing_email VARCHAR(100);