package com.hospital.hms.auth.entity;

public enum UserRole {
    ADMIN,
    PHARMACY_MANAGER,
    STORE_INCHARGE,
    IPD_PHARMACIST,
    PHARMACIST,
    DOCTOR,
    NURSE,
    IPD_MANAGER,
    BILLING,
    QUALITY_MANAGER,
    LAB_TECH,
    LAB_TECHNICIAN,
    LAB_SUPERVISOR,
    PATHOLOGIST,
    PHLEBOTOMIST,
    RADIOLOGY_TECH,
    BLOOD_BANK_TECH,
    RECEPTIONIST,
    FRONT_DESK,
    HELP_DESK,
    HOUSEKEEPING
}

